# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qie.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName(_fromUtf8("Widget"))
        Widget.resize(1375, 516)
        self.groupBox_singlePhotonCounts = QtGui.QGroupBox(Widget)
        self.groupBox_singlePhotonCounts.setGeometry(QtCore.QRect(250, 50, 521, 181))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_singlePhotonCounts.setFont(font)
        self.groupBox_singlePhotonCounts.setObjectName(_fromUtf8("groupBox_singlePhotonCounts"))
        self.label_A = QtGui.QLabel(self.groupBox_singlePhotonCounts)
        self.label_A.setGeometry(QtCore.QRect(50, 30, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_A.setFont(font)
        self.label_A.setObjectName(_fromUtf8("label_A"))
        self.label_B = QtGui.QLabel(self.groupBox_singlePhotonCounts)
        self.label_B.setGeometry(QtCore.QRect(180, 30, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_B.setFont(font)
        self.label_B.setObjectName(_fromUtf8("label_B"))
        self.label_C = QtGui.QLabel(self.groupBox_singlePhotonCounts)
        self.label_C.setGeometry(QtCore.QRect(310, 30, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_C.setFont(font)
        self.label_C.setObjectName(_fromUtf8("label_C"))
        self.label_D = QtGui.QLabel(self.groupBox_singlePhotonCounts)
        self.label_D.setGeometry(QtCore.QRect(440, 30, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_D.setFont(font)
        self.label_D.setObjectName(_fromUtf8("label_D"))
        self.textEdit_A = QtGui.QTextEdit(self.groupBox_singlePhotonCounts)
        self.textEdit_A.setGeometry(QtCore.QRect(10, 80, 101, 31))
        self.textEdit_A.setReadOnly(True)
        self.textEdit_A.setObjectName(_fromUtf8("textEdit_A"))
        self.textEdit_B = QtGui.QTextEdit(self.groupBox_singlePhotonCounts)
        self.textEdit_B.setGeometry(QtCore.QRect(140, 80, 101, 31))
        self.textEdit_B.setReadOnly(True)
        self.textEdit_B.setObjectName(_fromUtf8("textEdit_B"))
        self.textEdit_C = QtGui.QTextEdit(self.groupBox_singlePhotonCounts)
        self.textEdit_C.setGeometry(QtCore.QRect(270, 80, 101, 31))
        self.textEdit_C.setReadOnly(True)
        self.textEdit_C.setObjectName(_fromUtf8("textEdit_C"))
        self.textEdit_D = QtGui.QTextEdit(self.groupBox_singlePhotonCounts)
        self.textEdit_D.setGeometry(QtCore.QRect(400, 80, 101, 31))
        self.textEdit_D.setReadOnly(True)
        self.textEdit_D.setObjectName(_fromUtf8("textEdit_D"))
        self.label_warning = QtGui.QLabel(self.groupBox_singlePhotonCounts)
        self.label_warning.setEnabled(False)
        self.label_warning.setGeometry(QtCore.QRect(130, 130, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_warning.setFont(font)
        self.label_warning.setObjectName(_fromUtf8("label_warning"))
        self.groupBox_settings = QtGui.QGroupBox(Widget)
        self.groupBox_settings.setGeometry(QtCore.QRect(50, 50, 181, 411))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_settings.setFont(font)
        self.groupBox_settings.setObjectName(_fromUtf8("groupBox_settings"))
        self.pushButton_quit = QtGui.QPushButton(self.groupBox_settings)
        self.pushButton_quit.setGeometry(QtCore.QRect(30, 340, 111, 51))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_quit.setFont(font)
        self.pushButton_quit.setObjectName(_fromUtf8("pushButton_quit"))
        self.doubleSpinBox_updatePeriod = QtGui.QDoubleSpinBox(self.groupBox_settings)
        self.doubleSpinBox_updatePeriod.setGeometry(QtCore.QRect(30, 190, 62, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_updatePeriod.setFont(font)
        self.doubleSpinBox_updatePeriod.setDecimals(1)
        self.doubleSpinBox_updatePeriod.setSingleStep(0.1)
        self.doubleSpinBox_updatePeriod.setObjectName(_fromUtf8("doubleSpinBox_updatePeriod"))
        self.doubleSpinBox_coincidenceWindow = QtGui.QDoubleSpinBox(self.groupBox_settings)
        self.doubleSpinBox_coincidenceWindow.setGeometry(QtCore.QRect(30, 240, 62, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_coincidenceWindow.setFont(font)
        self.doubleSpinBox_coincidenceWindow.setDecimals(1)
        self.doubleSpinBox_coincidenceWindow.setSingleStep(0.1)
        self.doubleSpinBox_coincidenceWindow.setObjectName(_fromUtf8("doubleSpinBox_coincidenceWindow"))
        self.label_updatePeriod = QtGui.QLabel(self.groupBox_settings)
        self.label_updatePeriod.setGeometry(QtCore.QRect(30, 170, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_updatePeriod.setFont(font)
        self.label_updatePeriod.setObjectName(_fromUtf8("label_updatePeriod"))
        self.label_coincidenceWindow = QtGui.QLabel(self.groupBox_settings)
        self.label_coincidenceWindow.setGeometry(QtCore.QRect(30, 220, 141, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_coincidenceWindow.setFont(font)
        self.label_coincidenceWindow.setObjectName(_fromUtf8("label_coincidenceWindow"))
        self.pushButton_start = QtGui.QPushButton(self.groupBox_settings)
        self.pushButton_start.setGeometry(QtCore.QRect(10, 40, 71, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setObjectName(_fromUtf8("pushButton_start"))
        self.pushButton_stop = QtGui.QPushButton(self.groupBox_settings)
        self.pushButton_stop.setGeometry(QtCore.QRect(90, 40, 71, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setObjectName(_fromUtf8("pushButton_stop"))
        self.pushButton_export = QtGui.QPushButton(self.groupBox_settings)
        self.pushButton_export.setGeometry(QtCore.QRect(10, 130, 71, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_export.setFont(font)
        self.pushButton_export.setObjectName(_fromUtf8("pushButton_export"))
        self.textEdit_timeAmount = QtGui.QTextEdit(self.groupBox_settings)
        self.textEdit_timeAmount.setGeometry(QtCore.QRect(90, 80, 71, 31))
        self.textEdit_timeAmount.setAcceptRichText(True)
        self.textEdit_timeAmount.setObjectName(_fromUtf8("textEdit_timeAmount"))
        self.label_timeAmount = QtGui.QLabel(self.groupBox_settings)
        self.label_timeAmount.setGeometry(QtCore.QRect(20, 90, 61, 16))
        self.label_timeAmount.setObjectName(_fromUtf8("label_timeAmount"))
        self.groupBox_coincidenceCounts = QtGui.QGroupBox(Widget)
        self.groupBox_coincidenceCounts.setGeometry(QtCore.QRect(250, 250, 1081, 241))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_coincidenceCounts.setFont(font)
        self.groupBox_coincidenceCounts.setObjectName(_fromUtf8("groupBox_coincidenceCounts"))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox_coincidenceCounts)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 70, 91, 141))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_coincidenceValueLabels = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_coincidenceValueLabels.setMargin(11)
        self.verticalLayout_coincidenceValueLabels.setSpacing(6)
        self.verticalLayout_coincidenceValueLabels.setObjectName(_fromUtf8("verticalLayout_coincidenceValueLabels"))
        self.label_correctedCoincidences = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_correctedCoincidences.setFont(font)
        self.label_correctedCoincidences.setWordWrap(True)
        self.label_correctedCoincidences.setObjectName(_fromUtf8("label_correctedCoincidences"))
        self.verticalLayout_coincidenceValueLabels.addWidget(self.label_correctedCoincidences)
        self.label_statisticalCorrection = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_statisticalCorrection.setFont(font)
        self.label_statisticalCorrection.setWordWrap(True)
        self.label_statisticalCorrection.setObjectName(_fromUtf8("label_statisticalCorrection"))
        self.verticalLayout_coincidenceValueLabels.addWidget(self.label_statisticalCorrection)
        self.label_rawCoincidences = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_rawCoincidences.setFont(font)
        self.label_rawCoincidences.setWordWrap(True)
        self.label_rawCoincidences.setObjectName(_fromUtf8("label_rawCoincidences"))
        self.verticalLayout_coincidenceValueLabels.addWidget(self.label_rawCoincidences)
        self.widget = QtGui.QWidget(self.groupBox_coincidenceCounts)
        self.widget.setGeometry(QtCore.QRect(100, 30, 971, 31))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_coincidenceLabels = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_coincidenceLabels.setContentsMargins(25, 11, 11, 11)
        self.horizontalLayout_coincidenceLabels.setSpacing(20)
        self.horizontalLayout_coincidenceLabels.setObjectName(_fromUtf8("horizontalLayout_coincidenceLabels"))
        self.label_AB = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_AB.setFont(font)
        self.label_AB.setObjectName(_fromUtf8("label_AB"))
        self.horizontalLayout_coincidenceLabels.addWidget(self.label_AB)
        self.label_AC = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_AC.setFont(font)
        self.label_AC.setObjectName(_fromUtf8("label_AC"))
        self.horizontalLayout_coincidenceLabels.addWidget(self.label_AC)
        self.label_AD = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_AD.setFont(font)
        self.label_AD.setObjectName(_fromUtf8("label_AD"))
        self.horizontalLayout_coincidenceLabels.addWidget(self.label_AD)
        self.label_BC = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_BC.setFont(font)
        self.label_BC.setObjectName(_fromUtf8("label_BC"))
        self.horizontalLayout_coincidenceLabels.addWidget(self.label_BC)
        self.label_BD = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_BD.setFont(font)
        self.label_BD.setObjectName(_fromUtf8("label_BD"))
        self.horizontalLayout_coincidenceLabels.addWidget(self.label_BD)
        self.label_CD = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_CD.setFont(font)
        self.label_CD.setObjectName(_fromUtf8("label_CD"))
        self.horizontalLayout_coincidenceLabels.addWidget(self.label_CD)
        self.label_ABC = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_ABC.setFont(font)
        self.label_ABC.setObjectName(_fromUtf8("label_ABC"))
        self.horizontalLayout_coincidenceLabels.addWidget(self.label_ABC)
        self.label_BCD = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_BCD.setFont(font)
        self.label_BCD.setObjectName(_fromUtf8("label_BCD"))
        self.horizontalLayout_coincidenceLabels.addWidget(self.label_BCD)
        self.label_ACD = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_ACD.setFont(font)
        self.label_ACD.setObjectName(_fromUtf8("label_ACD"))
        self.horizontalLayout_coincidenceLabels.addWidget(self.label_ACD)
        self.label_ABD = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_ABD.setFont(font)
        self.label_ABD.setObjectName(_fromUtf8("label_ABD"))
        self.horizontalLayout_coincidenceLabels.addWidget(self.label_ABD)
        self.label_ABCD = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_ABCD.setFont(font)
        self.label_ABCD.setObjectName(_fromUtf8("label_ABCD"))
        self.horizontalLayout_coincidenceLabels.addWidget(self.label_ABCD)
        self.textEdit_AB = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_AB.setGeometry(QtCore.QRect(100, 80, 71, 31))
        self.textEdit_AB.setObjectName(_fromUtf8("textEdit_AB"))
        self.textEdit_AC = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_AC.setGeometry(QtCore.QRect(190, 80, 71, 31))
        self.textEdit_AC.setObjectName(_fromUtf8("textEdit_AC"))
        self.textEdit_AD = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_AD.setGeometry(QtCore.QRect(280, 80, 71, 31))
        self.textEdit_AD.setObjectName(_fromUtf8("textEdit_AD"))
        self.textEdit_BC = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_BC.setGeometry(QtCore.QRect(370, 80, 71, 31))
        self.textEdit_BC.setObjectName(_fromUtf8("textEdit_BC"))
        self.textEdit_BD = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_BD.setGeometry(QtCore.QRect(460, 80, 71, 31))
        self.textEdit_BD.setObjectName(_fromUtf8("textEdit_BD"))
        self.textEdit_CD = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_CD.setGeometry(QtCore.QRect(550, 80, 71, 31))
        self.textEdit_CD.setObjectName(_fromUtf8("textEdit_CD"))
        self.textEdit_ABC = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_ABC.setGeometry(QtCore.QRect(640, 80, 71, 31))
        self.textEdit_ABC.setObjectName(_fromUtf8("textEdit_ABC"))
        self.textEdit_BCD = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_BCD.setGeometry(QtCore.QRect(730, 80, 71, 31))
        self.textEdit_BCD.setObjectName(_fromUtf8("textEdit_BCD"))
        self.textEdit_ACD = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_ACD.setGeometry(QtCore.QRect(820, 80, 71, 31))
        self.textEdit_ACD.setObjectName(_fromUtf8("textEdit_ACD"))
        self.textEdit_ABD = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_ABD.setGeometry(QtCore.QRect(910, 80, 71, 31))
        self.textEdit_ABD.setObjectName(_fromUtf8("textEdit_ABD"))
        self.textEdit_ABCD = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_ABCD.setGeometry(QtCore.QRect(1000, 80, 71, 31))
        self.textEdit_ABCD.setObjectName(_fromUtf8("textEdit_ABCD"))
        self.textEdit_AB_2 = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_AB_2.setGeometry(QtCore.QRect(100, 130, 71, 31))
        self.textEdit_AB_2.setObjectName(_fromUtf8("textEdit_AB_2"))
        self.textEdit_AB_3 = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_AB_3.setGeometry(QtCore.QRect(100, 180, 71, 31))
        self.textEdit_AB_3.setObjectName(_fromUtf8("textEdit_AB_3"))
        self.textEdit_AC_2 = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_AC_2.setGeometry(QtCore.QRect(190, 130, 71, 31))
        self.textEdit_AC_2.setObjectName(_fromUtf8("textEdit_AC_2"))
        self.textEdit_AC_3 = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_AC_3.setGeometry(QtCore.QRect(190, 180, 71, 31))
        self.textEdit_AC_3.setObjectName(_fromUtf8("textEdit_AC_3"))
        self.textEdit_AD_2 = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_AD_2.setGeometry(QtCore.QRect(280, 130, 71, 31))
        self.textEdit_AD_2.setObjectName(_fromUtf8("textEdit_AD_2"))
        self.textEdit_AD_3 = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_AD_3.setGeometry(QtCore.QRect(280, 180, 71, 31))
        self.textEdit_AD_3.setObjectName(_fromUtf8("textEdit_AD_3"))
        self.textEdit_BC_2 = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_BC_2.setGeometry(QtCore.QRect(370, 130, 71, 31))
        self.textEdit_BC_2.setObjectName(_fromUtf8("textEdit_BC_2"))
        self.textEdit_BC_3 = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_BC_3.setGeometry(QtCore.QRect(370, 180, 71, 31))
        self.textEdit_BC_3.setObjectName(_fromUtf8("textEdit_BC_3"))
        self.textEdit_BD_2 = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_BD_2.setGeometry(QtCore.QRect(460, 130, 71, 31))
        self.textEdit_BD_2.setObjectName(_fromUtf8("textEdit_BD_2"))
        self.textEdit_BD_3 = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_BD_3.setGeometry(QtCore.QRect(460, 180, 71, 31))
        self.textEdit_BD_3.setObjectName(_fromUtf8("textEdit_BD_3"))
        self.textEdit_CD_2 = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_CD_2.setGeometry(QtCore.QRect(550, 130, 71, 31))
        self.textEdit_CD_2.setObjectName(_fromUtf8("textEdit_CD_2"))
        self.textEdit_CD_3 = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_CD_3.setGeometry(QtCore.QRect(550, 180, 71, 31))
        self.textEdit_CD_3.setObjectName(_fromUtf8("textEdit_CD_3"))
        self.textEdit_ABC_2 = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_ABC_2.setGeometry(QtCore.QRect(640, 130, 71, 31))
        self.textEdit_ABC_2.setObjectName(_fromUtf8("textEdit_ABC_2"))
        self.textEdit_ABC_3 = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_ABC_3.setGeometry(QtCore.QRect(640, 180, 71, 31))
        self.textEdit_ABC_3.setObjectName(_fromUtf8("textEdit_ABC_3"))
        self.textEdit_BCD_2 = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_BCD_2.setGeometry(QtCore.QRect(730, 130, 71, 31))
        self.textEdit_BCD_2.setObjectName(_fromUtf8("textEdit_BCD_2"))
        self.textEdit_BCD_3 = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_BCD_3.setGeometry(QtCore.QRect(730, 180, 71, 31))
        self.textEdit_BCD_3.setObjectName(_fromUtf8("textEdit_BCD_3"))
        self.textEdit_ACD_2 = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_ACD_2.setGeometry(QtCore.QRect(820, 130, 71, 31))
        self.textEdit_ACD_2.setObjectName(_fromUtf8("textEdit_ACD_2"))
        self.textEdit_ACD_3 = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_ACD_3.setGeometry(QtCore.QRect(820, 180, 71, 31))
        self.textEdit_ACD_3.setObjectName(_fromUtf8("textEdit_ACD_3"))
        self.textEdit_ABD_2 = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_ABD_2.setGeometry(QtCore.QRect(910, 130, 71, 31))
        self.textEdit_ABD_2.setObjectName(_fromUtf8("textEdit_ABD_2"))
        self.textEdit_ABD_3 = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_ABD_3.setGeometry(QtCore.QRect(910, 180, 71, 31))
        self.textEdit_ABD_3.setObjectName(_fromUtf8("textEdit_ABD_3"))
        self.textEdit_ABCD_2 = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_ABCD_2.setGeometry(QtCore.QRect(1000, 130, 71, 31))
        self.textEdit_ABCD_2.setObjectName(_fromUtf8("textEdit_ABCD_2"))
        self.textEdit_ABCD_3 = QtGui.QTextEdit(self.groupBox_coincidenceCounts)
        self.textEdit_ABCD_3.setGeometry(QtCore.QRect(1000, 180, 71, 31))
        self.textEdit_ABCD_3.setObjectName(_fromUtf8("textEdit_ABCD_3"))

        self.retranslateUi(Widget)
        QtCore.QObject.connect(self.pushButton_quit, QtCore.SIGNAL(_fromUtf8("clicked()")), Widget.close)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(_translate("Widget", "Widget", None))
        self.groupBox_singlePhotonCounts.setTitle(_translate("Widget", "Single Photon Counts", None))
        self.label_A.setText(_translate("Widget", "A", None))
        self.label_B.setText(_translate("Widget", "B", None))
        self.label_C.setText(_translate("Widget", "C", None))
        self.label_D.setText(_translate("Widget", "D", None))
        self.label_warning.setText(_translate("Widget", "<html><head/><body><p><span style=\" color:#ff0000;\">HIGH COUNT WARNING!</span></p></body></html>", None))
        self.groupBox_settings.setTitle(_translate("Widget", "Settings", None))
        self.pushButton_quit.setText(_translate("Widget", "QUIT", None))
        self.label_updatePeriod.setText(_translate("Widget", "Update Period", None))
        self.label_coincidenceWindow.setText(_translate("Widget", "Coincidence Window", None))
        self.pushButton_start.setText(_translate("Widget", "Start", None))
        self.pushButton_stop.setText(_translate("Widget", "Stop", None))
        self.pushButton_export.setText(_translate("Widget", "Export", None))
        self.label_timeAmount.setText(_translate("Widget", "Time (s):", None))
        self.groupBox_coincidenceCounts.setTitle(_translate("Widget", "Coincidence Counts", None))
        self.label_correctedCoincidences.setText(_translate("Widget", "Corrected Coincidences", None))
        self.label_statisticalCorrection.setText(_translate("Widget", "Statistical Correction", None))
        self.label_rawCoincidences.setText(_translate("Widget", "Raw Coincidences", None))
        self.label_AB.setText(_translate("Widget", "AB", None))
        self.label_AC.setText(_translate("Widget", "AC", None))
        self.label_AD.setText(_translate("Widget", "AD", None))
        self.label_BC.setText(_translate("Widget", "BC", None))
        self.label_BD.setText(_translate("Widget", "BD", None))
        self.label_CD.setText(_translate("Widget", "CD", None))
        self.label_ABC.setText(_translate("Widget", "ABC", None))
        self.label_BCD.setText(_translate("Widget", "BCD", None))
        self.label_ACD.setText(_translate("Widget", "ACD", None))
        self.label_ABD.setText(_translate("Widget", "ABD", None))
        self.label_ABCD.setText(_translate("Widget", "ABCD", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Widget = QtGui.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())

